### ISSUE TITLE
Counter-drone mod

### ISSUE THREAD

**Issue by DrChaos-Z1** [tfchaos-s4/tfc-s4#105]
**Link and Description**
Link: https://steamcommunity.com/sharedfiles/filedetails/?id=3018212379
Description: Mod that counters and jams drones.

**Does your requested mod/feature add significant value to the unit**
[Y/N] and Describe: Yes if we want to incorporate more drone types of warfare into missions

**Comment by PDTFawks** [comment]
Does not appear to be very functional at the moment. Can revisit in the future once functionality is added.
