### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by Ghostlyshell617** [tfchaos-s4/tfc-s4#113]
**Link and Description**
Link: https://steamcommunity.com/sharedfiles/filedetails/?id=2583277104
Description: A mod adding sounds for improved ambience, the sounds can be played with "play sound" module, and are all set to loop.

**Does your requested mod/feature add significant value to the unit**
[Y/N] and Describe: Yes, this mod adds US, RU, and Civilian chatter as well as other ambient sound effects like a mechanics shop, civilian market, animal noises, etc that i think will help with the zeus increasing immersion a lot.

**Comment by PDTFawks** [comment]
Added in latest update
