### ISSUE TITLE
Stamina is enabled on Server #1 and #2

### ISSUE THREAD

**Issue by tfc-s4** [tfchaos-s4/tfc-s4#32]
**Describe the bug**
As titled.

**To Reproduce**
1. Run around.

**Expected behavior**
No stamina...

**Screenshots**

**Additional context**

**Comment by TonyCaput0** [comment]
possible fixes:

- arma does not like the passing off of missions to be put in server, and settings are being lost in translation. 

- making sure **enable stamina** is turned off on all playable units 

- [player enableStamina false] is in attributes>general>init. 
   -with and without a ";"
