### ISSUE TITLE
Lag when mortars/ZSUs/M134s are fired

### ISSUE THREAD

**Issue by tfc-s4** [tfchaos-s4/tfc-s4#33]
**Describe the bug**
As titled

**To Reproduce**
1. Fire and of the above.

**Expected behavior**
Shouldn't lag as bad.

**Screenshots**

**Additional context**

**Comment by TonyCaput0** [comment]
possible fixes

- removing bloodlust/blastcore/photon smoke fix

**Comment by tfc-s4** [comment]
Fixed by reducing amount off blood effects produced by bloodlust on explosions/higher caliber hits.
