### ISSUE TITLE
Uzbin Valley

### ISSUE THREAD

**Issue by TonyCaput0** [tfchaos-s4/tfc-s4#48]
**Link and Description**
Link: https://steamcommunity.com/sharedfiles/filedetails/?id=1882424760&searchtext=uzbin
Description: Valley located in Afghanistan

**Does your requested mod/feature add significant value to the unit**
[Y/N] and Describe: Very gorgeous map with multiple cities. Would be INCREDIBLE to play on.

**Comment by tfc-s4** [comment]
Map added.
