### ISSUE TITLE
5th server for the IFA3 (Iron Front Arma 3) mod and Spearhead '44 CDLC

### ISSUE THREAD

**Issue by Ghostlyshell617** [tfchaos-s4/tfc-s4#52]
**Link and Description**
Link: https://steamcommunity.com/workshop/filedetails/?id=2648308937
https://store.steampowered.com/app/1175380/Arma_3_Creator_DLC_Spearhead_1944/
Description: World War 2 modpack and CDLC

**Does your requested mod/feature add significant value to the unit**
[Y/N] and Describe: For a while now I have wanted to get a modlist going for world war 2 operations in tfc, and recently there has been support for it with quite a few guys attending fun ops I have been hosting on local servers. For the full experience it would be much easier to have the mod and dlc on a dedicated server for performance and accessibility.  I am not 100% sure if Spearhead '44 is compatible with IFA3 and if guys could play on the server if they install IFA3 but dont own Spearhead '44, if they are not compatible or if it is just too much or a hassle it would be much preferred to just stick with IFA3. Lower quality assets but the download size will be smaller and it is free.

**Comment by Ghostlyshell617** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3009239431&searchtext=direct+action+normandy

[TFC_WW2.zip](https://github.com/user-attachments/files/17769489/TFC_WW2.zip)

**Comment by tfc-s4** [comment]
Server created.
