### ISSUE TITLE
Dublin Cyanosis

### ISSUE THREAD

**Issue by TonyCaput0** [tfchaos-s4/tfc-s4#54]
**Describe the bug**
Dublin was experiencing cyanosis on both arms when standing at arsenal on training map, and also would pass out at 3K altitude. 

**To Reproduce**
Could not reproduce

**Expected behavior**
cyanosis should develop, and player will die
**Screenshots**

**Comment by tfc-s4** [comment]
Hasn't been brought up since. Assuming it has been resolved.
