### ISSUE TITLE
CUP CWA missing

### ISSUE THREAD

**Issue by DrChaos-Z1** [tfchaos-s4/tfc-s4#66]
**Describe the bug**
Not quite sure. This error in picture pops up constantly during mission testing

**To Reproduce**
It just happens when I test eden missions on local multiplayer

**Expected behavior**
See if this is a larger issue or just my end

**Screenshots**
![error](https://github.com/user-attachments/assets/4b8a2a97-ffb8-4ac2-a43a-7712c3554cc6)

**Additional context**
I don't know if it has to do with vehicles or artillery or what.

**Comment by TonyCaput0** [comment]
For some reason arma will pop out certain errors when doing eden missions by yourself. I'm not sure why, perhaps Newton has a better answer. But i wouldn't worry about it. As long as it isn't breaking your game
